import { Drill } from '@/types/app';

export const drills: Drill[] = [
  // === SHOOTING ===
  { id: 's1', name: 'Form Shooting', category: 'shooting', difficulty: 1, duration: 300, reps: 50, equipment: ['hoop'], description: 'Close-range one-hand form shots focusing on wrist snap and follow-through.', tip: 'Keep your elbow under the ball and flick your wrist like reaching into a cookie jar on a high shelf.', skillLevel: ['beginner', 'intermediate', 'advanced'] },
  { id: 's2', name: 'Free Throw Routine', category: 'shooting', difficulty: 1, duration: 600, reps: 30, equipment: ['hoop'], description: 'Shoot 30 free throws with a consistent pre-shot routine.', tip: 'Develop a rhythm: dribble twice, spin the ball, bend knees, shoot. Same routine every time.', skillLevel: ['beginner', 'intermediate', 'advanced'] },
  { id: 's3', name: 'Elbow Jumpers', category: 'shooting', difficulty: 2, duration: 480, reps: 40, equipment: ['hoop'], description: 'Mid-range jumpers from both elbows, alternating sides.', tip: 'Square your shoulders to the basket and land in the same spot you jumped from.', skillLevel: ['intermediate', 'advanced'] },
  { id: 's4', name: 'Catch & Shoot 3s', category: 'shooting', difficulty: 2, duration: 600, reps: 30, equipment: ['hoop'], description: 'Simulate catch-and-shoot situations from five spots behind the arc.', tip: 'Have your feet set before the ball arrives. Hands ready, knees loaded.', skillLevel: ['intermediate', 'advanced'] },
  { id: 's5', name: 'Pull-Up Jumpers', category: 'shooting', difficulty: 3, duration: 600, reps: 25, equipment: ['hoop'], description: 'Drive from the three-point line, stop on a dime, and pull up for a mid-range shot.', tip: 'Use a 1-2 step stop to create balance. The stop IS the shot.', skillLevel: ['advanced'] },
  { id: 's6', name: 'Bank Shot Practice', category: 'shooting', difficulty: 2, duration: 420, reps: 30, equipment: ['hoop'], description: 'Practice bank shots from 45-degree angles on both sides.', tip: 'Aim for the top corner of the square on the backboard. Soft touch wins.', skillLevel: ['beginner', 'intermediate'] },
  { id: 's7', name: 'Floater Drill', category: 'shooting', difficulty: 3, duration: 480, reps: 20, equipment: ['hoop'], description: 'Drive into the lane and release a high-arcing floater over imaginary shot-blockers.', tip: 'Push the ball up, don\'t shoot it forward. High arc = soft landing.', skillLevel: ['intermediate', 'advanced'] },
  { id: 's8', name: 'Spot-Up Shooting', category: 'shooting', difficulty: 1, duration: 600, reps: 50, equipment: ['hoop'], description: 'Shoot from 5 designated spots. 10 shots each. Track your percentage.', tip: 'Follow through and hold your hand up until the ball hits the rim. Watch your arc.', skillLevel: ['beginner', 'intermediate', 'advanced'] },
  { id: 's9', name: 'Off-Screen Shooting', category: 'shooting', difficulty: 3, duration: 600, reps: 20, equipment: ['hoop', 'cones'], description: 'Set up cones as screens. Curl, fade, or pop for catch-and-shoot jumpers.', tip: 'Read the screen: curl tight for open looks, fade when the defender trails.', skillLevel: ['advanced'] },
  { id: 's10', name: 'One-Dribble Pull-Up', category: 'shooting', difficulty: 2, duration: 480, reps: 30, equipment: ['hoop'], description: 'One hard dribble left or right from the wing, then pull up for a jumper.', tip: 'Pound the dribble hard to create separation. Gather low, rise up tall.', skillLevel: ['intermediate', 'advanced'] },

  // === DRIBBLING ===
  { id: 'd1', name: 'Stationary Pound Dribble', category: 'dribbling', difficulty: 1, duration: 180, equipment: ['none'], description: 'Pound the ball hard at knee height. 30 seconds each hand, 3 sets.', tip: 'Push the ball into the ground—don\'t slap at it. Fingertips, not palm.', skillLevel: ['beginner', 'intermediate'] },
  { id: 'd2', name: 'Crossover Series', category: 'dribbling', difficulty: 2, duration: 300, equipment: ['none'], description: 'Stationary crossovers: regular, between-the-legs, behind-the-back. 20 each.', tip: 'Keep the ball below your knees on crossovers. Low and tight = hard to steal.', skillLevel: ['beginner', 'intermediate', 'advanced'] },
  { id: 'd3', name: 'Full-Court Dribbling', category: 'dribbling', difficulty: 2, duration: 480, equipment: ['none'], description: 'Dribble full court using different moves: crossover down, behind-back back.', tip: 'Keep your head up. If you\'re looking at the ball, a defender is already ahead of you.', skillLevel: ['intermediate', 'advanced'] },
  { id: 'd4', name: 'Cone Weave Dribbling', category: 'dribbling', difficulty: 2, duration: 360, equipment: ['cones'], description: 'Set up 5 cones in a line. Weave through using different dribble moves.', tip: 'Attack each cone like it\'s a defender. Change speed AND direction at each one.', skillLevel: ['beginner', 'intermediate', 'advanced'] },
  { id: 'd5', name: 'Spider Dribble', category: 'dribbling', difficulty: 3, duration: 180, equipment: ['none'], description: 'Legs wide, ball between legs: right-right-left-left pattern without stopping.', tip: 'Start slow until the rhythm clicks. Speed comes after the pattern is automatic.', skillLevel: ['intermediate', 'advanced'] },
  { id: 'd6', name: 'Two-Ball Dribbling', category: 'dribbling', difficulty: 3, duration: 300, equipment: ['none'], description: 'Dribble two balls simultaneously: together, alternating, crossover.', tip: 'Start with both balls hitting the floor at the same time, then alternate.', skillLevel: ['advanced'] },
  { id: 'd7', name: 'Tennis Ball Dribbling', category: 'dribbling', difficulty: 3, duration: 300, equipment: ['none'], description: 'Dribble a basketball with one hand while catching/tossing a tennis ball with the other.', tip: 'This trains your peripheral awareness. Keep your dribble alive no matter what the off-hand does.', skillLevel: ['advanced'] },
  { id: 'd8', name: 'Kill Dribble Series', category: 'dribbling', difficulty: 2, duration: 240, equipment: ['none'], description: 'Practice hesitation (kill) dribble moves: jab, shoulder fake, speed change.', tip: 'The hesitation sells the move. Slow-slow-FAST makes defenders freeze.', skillLevel: ['intermediate', 'advanced'] },
  { id: 'd9', name: 'Figure-8 Dribble', category: 'dribbling', difficulty: 1, duration: 180, equipment: ['none'], description: 'Weave the ball in a figure-8 around and between your legs while stationary.', tip: 'Stay low in an athletic stance. The lower you are, the faster you can go.', skillLevel: ['beginner', 'intermediate'] },
  { id: 'd10', name: 'Retreat Dribble', category: 'dribbling', difficulty: 2, duration: 300, equipment: ['cones'], description: 'Attack forward 3 dribbles, retreat dribble back 2, then attack again past the cone.', tip: 'Push off your front foot hard on the retreat. Protect the ball on your hip.', skillLevel: ['intermediate', 'advanced'] },

  // === FOOTWORK ===
  { id: 'f1', name: 'Triple Threat Pivots', category: 'footwork', difficulty: 1, duration: 300, equipment: ['none'], description: 'Practice front pivots and reverse pivots from triple threat position. 10 each direction.', tip: 'Stay on the ball of your pivot foot. Flat feet = slow feet.', skillLevel: ['beginner', 'intermediate'] },
  { id: 'f2', name: 'Defensive Slides', category: 'footwork', difficulty: 1, duration: 300, equipment: ['none'], description: 'Slide side to side across the lane in defensive stance. 5 sets of 10 slides.', tip: 'Never cross your feet. Push off the trailing foot and stay low.', skillLevel: ['beginner', 'intermediate', 'advanced'] },
  { id: 'f3', name: 'Drop Step Drill', category: 'footwork', difficulty: 2, duration: 360, equipment: ['hoop'], description: 'Post up on the block, drop step baseline and middle for layups. 10 each side.', tip: 'Seal the defender with your body. One big step past them, then power up.', skillLevel: ['intermediate', 'advanced'] },
  { id: 'f4', name: 'Euro Step Drill', category: 'footwork', difficulty: 2, duration: 360, equipment: ['hoop'], description: 'Practice euro step finishes from both wings. Focus on the gather step.', tip: 'First step goes one way, second step goes the OTHER way. Exaggerate the change of direction.', skillLevel: ['intermediate', 'advanced'] },
  { id: 'f5', name: 'Jab Step Series', category: 'footwork', difficulty: 1, duration: 240, equipment: ['none'], description: 'From triple threat: jab step, jab-and-go, jab-and-shoot. 10 each.', tip: 'A great jab step is short, quick, and believable. Make the defender react.', skillLevel: ['beginner', 'intermediate', 'advanced'] },
  { id: 'f6', name: 'Closeout Drill', category: 'footwork', difficulty: 2, duration: 300, equipment: ['cones'], description: 'Sprint to a cone, break down into defensive stance, slide laterally.', tip: 'Chop your feet as you approach. Short choppy steps = controlled stop.', skillLevel: ['intermediate', 'advanced'] },
  { id: 'f7', name: 'Ladder Quick Feet', category: 'footwork', difficulty: 1, duration: 300, equipment: ['none'], description: 'Imagine a ladder on the ground. Quick feet in-and-out patterns.', tip: 'Arms drive your feet. Pump your arms fast and your feet will follow.', skillLevel: ['beginner', 'intermediate', 'advanced'] },
  { id: 'f8', name: 'Spin Move Footwork', category: 'footwork', difficulty: 3, duration: 360, equipment: ['hoop'], description: 'Practice spin moves into the lane from both wings. Focus on keeping the ball tight.', tip: 'Plant your inside foot, reverse pivot 180°, and explode to the rim. Ball stays on your hip.', skillLevel: ['advanced'] },
  { id: 'f9', name: 'Step-Back Jumper Footwork', category: 'footwork', difficulty: 3, duration: 360, equipment: ['hoop'], description: 'Practice step-back moves from the mid-range. Focus on creating space.', tip: 'Push off your front foot explosively. Land balanced with feet shoulder-width apart.', skillLevel: ['advanced'] },
  { id: 'f10', name: 'Box Jump to Sprint', category: 'footwork', difficulty: 2, duration: 300, equipment: ['none'], description: 'Perform 3 squat jumps, then immediately sprint 10 yards. 5 sets.', tip: 'Land softly with bent knees, then explode into your sprint. Quick transition is key.', skillLevel: ['intermediate', 'advanced'] },

  // === CONDITIONING ===
  { id: 'c1', name: 'Suicide Sprints', category: 'conditioning', difficulty: 2, duration: 600, equipment: ['none'], description: 'Classic suicide sprints: free throw line, half court, far free throw, full court. 5 sets.', tip: 'Touch the line with your hand every time. Bend at the hips, not the waist, to decelerate.', skillLevel: ['beginner', 'intermediate', 'advanced'] },
  { id: 'c2', name: 'Jump Rope Intervals', category: 'conditioning', difficulty: 1, duration: 600, equipment: ['jump_rope'], description: '30 seconds fast, 30 seconds rest. 10 rounds. Mix in high knees and double-unders.', tip: 'Stay on the balls of your feet. Small, quick bounces—the rope does the work.', skillLevel: ['beginner', 'intermediate', 'advanced'] },
  { id: 'c3', name: 'Wall Sits', category: 'conditioning', difficulty: 1, duration: 300, equipment: ['none'], description: 'Wall sit for 45 seconds, rest 15 seconds. 4 rounds. Builds leg endurance.', tip: 'Thighs parallel to the floor, back flat against the wall. Don\'t let your knees go past your toes.', skillLevel: ['beginner', 'intermediate', 'advanced'] },
  { id: 'c4', name: 'Burpee + Sprint', category: 'conditioning', difficulty: 3, duration: 480, equipment: ['none'], description: '5 burpees then sprint 20 yards. Jog back. 8 rounds.', tip: 'Explode out of the burpee directly into your sprint. No pause between.', skillLevel: ['intermediate', 'advanced'] },
  { id: 'c5', name: 'Plank to Push-Up', category: 'conditioning', difficulty: 2, duration: 360, equipment: ['none'], description: 'Alternate between forearm plank and push-up position. 30 seconds on, 15 seconds rest, 6 rounds.', tip: 'Keep your core tight and hips level. Don\'t rock side to side as you transition.', skillLevel: ['beginner', 'intermediate', 'advanced'] },
  { id: 'c6', name: 'Mountain Climbers', category: 'conditioning', difficulty: 2, duration: 300, equipment: ['none'], description: '30 seconds of mountain climbers, 15 seconds rest. 8 rounds.', tip: 'Drive your knees to your chest. Keep your back flat—imagine a glass of water on it.', skillLevel: ['beginner', 'intermediate', 'advanced'] },
  { id: 'c7', name: 'Resistance Band Squats', category: 'conditioning', difficulty: 2, duration: 360, equipment: ['resistance_band'], description: 'Banded squats with pause at the bottom. 4 sets of 15.', tip: 'Push your knees out against the band. This activates your glutes for explosive jumping.', skillLevel: ['intermediate', 'advanced'] },
  { id: 'c8', name: '17s (Sideline Sprints)', category: 'conditioning', difficulty: 3, duration: 480, equipment: ['none'], description: 'Sprint sideline to sideline 17 times. Rest 2 minutes. Repeat 3 times.', tip: 'This is a game-condition drill. Push through the fatigue—4th quarter legs are made here.', skillLevel: ['advanced'] },
  { id: 'c9', name: 'Lunge Walk', category: 'conditioning', difficulty: 1, duration: 300, equipment: ['none'], description: 'Walking lunges for 20 yards, turn around, come back. 4 sets.', tip: 'Step far enough that your back knee nearly touches the ground. Upright torso.', skillLevel: ['beginner', 'intermediate'] },
  { id: 'c10', name: 'Box Jumps', category: 'conditioning', difficulty: 2, duration: 300, equipment: ['none'], description: 'Jump onto a bench or sturdy surface. 4 sets of 10. Step down, don\'t jump down.', tip: 'Swing your arms up as you jump. Land softly with your whole foot on the surface.', skillLevel: ['intermediate', 'advanced'] },

  // === AGILITY ===
  { id: 'a1', name: 'Cone Shuffle Drill', category: 'agility', difficulty: 1, duration: 300, equipment: ['cones'], description: 'Set up 4 cones in a square. Shuffle between them: forward, lateral, backward, lateral.', tip: 'Stay low in an athletic stance. Quick feet, don\'t cross over.', skillLevel: ['beginner', 'intermediate', 'advanced'] },
  { id: 'a2', name: 'T-Drill', category: 'agility', difficulty: 2, duration: 360, equipment: ['cones'], description: 'Set cones in a T shape. Sprint forward, shuffle left, shuffle right, backpedal. 5 rounds.', tip: 'Explode out of each change of direction. The transition IS the drill.', skillLevel: ['intermediate', 'advanced'] },
  { id: 'a3', name: 'Pro Agility (5-10-5)', category: 'agility', difficulty: 2, duration: 300, equipment: ['cones'], description: 'Classic 5-10-5 shuttle: 5 yards right, 10 yards left, 5 yards right. 6 reps.', tip: 'Stay low through the turns. Plant your outside foot hard and drive.', skillLevel: ['intermediate', 'advanced'] },
  { id: 'a4', name: 'Zig-Zag Sprint', category: 'agility', difficulty: 2, duration: 360, equipment: ['cones'], description: 'Set cones in a zig-zag. Sprint to each cone, plant and cut. 5 rounds.', tip: 'Attack each cone at full speed. Decelerate late and accelerate early out of the cut.', skillLevel: ['beginner', 'intermediate', 'advanced'] },
  { id: 'a5', name: 'Reaction Sprint Drill', category: 'agility', difficulty: 3, duration: 360, equipment: ['none'], description: 'Start in defensive stance. On a mental cue, sprint in a random direction for 3 seconds. 10 reps.', tip: 'First step wins. Explode from your stance—no false steps.', skillLevel: ['intermediate', 'advanced'] },
  { id: 'a6', name: 'Lateral Bound', category: 'agility', difficulty: 2, duration: 300, equipment: ['none'], description: 'Single-leg lateral bounds: jump sideways, land on opposite foot, hold 1 sec. 4x10 each side.', tip: 'Stick each landing. If you can\'t balance, shorten the distance.', skillLevel: ['intermediate', 'advanced'] },
  { id: 'a7', name: 'Backpedal to Sprint', category: 'agility', difficulty: 2, duration: 300, equipment: ['cones'], description: 'Backpedal 10 yards, then flip hips and sprint 20 yards. 6 reps each direction.', tip: 'Open your hips toward where you\'re sprinting. Don\'t turn your back—flip and go.', skillLevel: ['intermediate', 'advanced'] },
  { id: 'a8', name: 'Dot Drill', category: 'agility', difficulty: 1, duration: 240, equipment: ['none'], description: 'Imagine 5 dots in a dice pattern. Jump between them in patterns: all 5, right foot, left foot.', tip: 'Quick, precise jumps. Land on the balls of your feet every time.', skillLevel: ['beginner', 'intermediate'] },
  { id: 'a9', name: 'Karaoke (Carioca)', category: 'agility', difficulty: 1, duration: 240, equipment: ['none'], description: 'Lateral movement crossing feet over and under. 20 yards each direction, 4 sets.', tip: 'Rotate your hips, not just your feet. Upper body stays facing forward.', skillLevel: ['beginner', 'intermediate', 'advanced'] },
  { id: 'a10', name: 'Four Corners Agility', category: 'agility', difficulty: 3, duration: 360, equipment: ['cones'], description: 'Sprint, backpedal, shuffle, and carioca around a square. Alternate directions. 6 rounds.', tip: 'Smooth transitions between movements. Don\'t slow down at the corners—accelerate through them.', skillLevel: ['advanced'] },
];

export function getDrillById(id: string): Drill | undefined {
  return drills.find(d => d.id === id);
}

export function getDrillsByCategory(category: Drill['category']): Drill[] {
  return drills.filter(d => d.category === category);
}

export function getFilteredDrills(
  skillLevel: Drill['skillLevel'][0],
  equipment: Drill['equipment'][0][],
  category?: Drill['category']
): Drill[] {
  return drills.filter(d => {
    if (!d.skillLevel.includes(skillLevel)) return false;
    if (d.equipment.some(e => e !== 'none' && !equipment.includes(e))) return false;
    if (category && d.category !== category) return false;
    return true;
  });
}
